services:
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    networks:
      - ecommerce-network
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9411" ]
      interval: 10s
      timeout: 5s
      retries: 5

  order-db:
    image: postgres:latest
    container_name: order-db
    environment:
      - POSTGRES_DB=eCommerce-orderDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Manish@2009
    networks:
      - ecommerce-network
    volumes:
      - orderDB-db-data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d eCommerce-orderDB" ]
      interval: 10s
      timeout: 5s
      retries: 5

  inventory-db:
    image: postgres:latest
    container_name: inventory-db
    environment:
      - POSTGRES_DB=eCommerce-inventoryDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Manish@2009
    networks:
      - ecommerce-network
    volumes:
      - inventoryDB-db-data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d eCommerce-inventoryDB" ]
      interval: 10s
      timeout: 5s
      retries: 5

  discovery-service:
    image: manishrnl/ecommerce-discovery-service:latest
    container_name: discovery-service
    user: root
    working_dir: /app
    networks:
      - ecommerce-network
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "8761" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  config-server:
    image: manishrnl/ecommerce-config-server:latest
    container_name: config-server
    user: root
    working_dir: /app
    networks:
      - ecommerce-network
    depends_on:
      discovery-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 8888 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  inventory-service:
    image: manishrnl/ecommerce-inventory-service:latest
    container_name: inventory-service
    user: root
    working_dir: /app
    volumes:
      - ./logs/inventory-service:/app/logs/inventory-service
    networks:
      - ecommerce-network
    depends_on:
      config-server:
        condition: service_healthy
      zipkin:
        condition: service_healthy
      inventory-db:
        condition: service_healthy

  order-service:
    image: manishrnl/ecommerce-order-service:latest
    container_name: order-service
    user: root
    working_dir: /app
    volumes:
      - ./logs/order-service:/app/logs/order-service
    networks:
      - ecommerce-network
    depends_on:
      config-server:
        condition: service_healthy
      zipkin:
        condition: service_healthy
      order-db:
        condition: service_healthy

  api-gateway:
    image: manishrnl/ecommerce-api-gateway:latest
    container_name: api-gateway
    user: root
    working_dir: /app
    volumes:
      - ./logs/api-gateway:/app/logs/api-gateway
    networks:
      - ecommerce-network
    depends_on:
      order-service:
        condition: service_started
      inventory-service:
        condition: service_started
    ports:
      - "8080:8080"

volumes:
  orderDB-db-data:
  inventoryDB-db-data:

networks:
  ecommerce-network:
    driver: bridge
